version: "3.9"

services:
  workspace:
    build:
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    container_name: react-ts-sample-workspace
    tty: true
    volumes:
      - .:/work/react-ts-sample
      - react-ts-sample_node_modules_volume:/work/react-ts-sample/node_modules
    working_dir: /work/react-ts-sample
    ports:
      - 3001:3000

volumes:
  react-ts-sample_node_modules_volume:
